
export interface Artist {
    name: string;
    imageUrl: string;
}

export const artists: Artist[] = [
    { name: "Arijit Singh", imageUrl: "https://picsum.photos/seed/arijit/200/200" },
    { name: "Neha Kakkar", imageUrl: "https://picsum.photos/seed/neha/200/200" },
    { name: "Shreya Ghoshal", imageUrl: "https://picsum.photos/seed/shreya/200/200" },
    { name: "Jubin Nautiyal", imageUrl: "https://picsum.photos/seed/jubin/200/200" },
    { name: "A. R. Rahman", imageUrl: "https://picsum.photos/seed/arrahman/200/200" },
    { name: "Lata Mangeshkar", imageUrl: "https://picsum.photos/seed/lata/200/200" },
    { name: "Sonu Nigam", imageUrl: "https://picsum.photos/seed/sonu/200/200" },
    { name: "Kishore Kumar", imageUrl: "https://picsum.photos/seed/kishore/200/200" },
    { name: "Udit Narayan", imageUrl: "https://picsum.photos/seed/udit/200/200" },
    { name: "Alka Yagnik", imageUrl: "https://picsum.photos/seed/alka/200/200" },
    { name: "Badshah", imageUrl: "https://picsum.photos/seed/badshah/200/200" },
    { name: "Honey Singh", imageUrl: "https://picsum.photos/seed/honey/200/200" },
    { name: "Guru Randhawa", imageUrl: "https://picsum.photos/seed/guru/200/200" },
    { name: "Diljit Dosanjh", imageUrl: "https://picsum.photos/seed/diljit/200/200" },
    { name: "Armaan Malik", imageUrl: "https://picsum.photos/seed/armaan/200/200" },
    { name: "Sunidhi Chauhan", imageUrl: "https://picsum.photos/seed/sunidhi/200/200" },
    { name: "Shankar Mahadevan", imageUrl: "https://picsum.photos/seed/shankar/200/200" },
    { name: "Anirudh Ravichander", imageUrl: "https://picsum.photos/seed/anirudh/200/200" },
    { name: "S. P. Balasubrahmanyam", imageUrl: "https://picsum.photos/seed/spb/200/200" },
    { name: "K.S. Chithra", imageUrl: "https://picsum.photos/seed/chithra/200/200" },
    { name: "Hariharan", imageUrl: "https://picsum.photos/seed/hariharan/200/200" },
    { name: "Sid Sriram", imageUrl: "https://picsum.photos/seed/sidsriram/200/200" },
    { name: "Atif Aslam", imageUrl: "https://picsum.photos/seed/atif/200/200" },
    { name: "Rahat Fateh Ali Khan", imageUrl: "https://picsum.photos/seed/rahat/200/200" },
    { name: "Ankit Tiwari", imageUrl: "https://picsum.photos/seed/ankit/200/200" },
    { name: "KK", imageUrl: "https://picsum.photos/seed/kk/200/200" },
    { name: "Mohit Chauhan", imageUrl: "https://picsum.photos/seed/mohit/200/200" },
    { name: "Shaan", imageUrl: "https://picsum.photos/seed/shaan/200/200" },
_   { name: "Pritam", imageUrl: "https://picsum.photos/seed/pritam/200/200" },
    { name: "Vishal-Shekhar", imageUrl: "https://picsum.photos/seed/vishalshekhar/200/200" },
    { name: "Amit Trivedi", imageUrl: "https://picsum.photos/seed/amittrivedi/200/200" },
    { name: "Mika Singh", imageUrl: "https://picsum.photos/seed/mika/200/200" },
    { name: "Dhvani Bhanushali", imageUrl: "https://picsum.photos/seed/dhvani/200/200" },
    { name: "Tulsi Kumar", imageUrl: "https://picsum.photos/seed/tulsi/200/200" },
    { name: "Darshan Raval", imageUrl: "https://picsum.photos/seed/darshan/200/200" },
    { name: "Kumar Sanu", imageUrl: "https://picsum.photos/seed/sanukumar/200/200" },
    { name: "Anuradha Paudwal", imageUrl: "https://picsum.photos/seed/anuradha/200/200" },
    { name: "Kavita Krishnamurthy", imageUrl: "https://picsum.photos/seed/kavita/200/200" },
    { name: "Sukhwinder Singh", imageUrl: "https://picsum.photos/seed/sukhwinder/200/200" },
    { name: "Jagjit Singh", imageUrl: "https://picsum.photos/seed/jagjit/200/200" },
    { name: "Ghulam Ali", imageUrl: "https://picsum.photos/seed/ghulamali/200/200" },
_   { name: "Nusrat Fateh Ali Khan", imageUrl: "https://picsum.photos/seed/nusrat/200/200" },
    { name: "Kailash Kher", imageUrl: "https://picsum.photos/seed/kailash/200 činn" },
    { name: "Papon", imageUrl: "https://picsum.photos/seed/papon/200/200" },
    { name: "Lucky Ali", imageUrl: "https://picsum.photos/seed/luckyali/200/200" },
    { name: "Ilaiyaraaja", imageUrl: "https://picsum.photos/seed/ilaiyaraaja/200/200" },
    { name: "Harris Jayaraj", imageUrl: "https://picsum.photos/seed/harris/200/200" },
    { name: "Yuvan Shankar Raja", imageUrl: "https://picsum.photos/seed/yuvan/200/200" },
    { name: "G. V. Prakash Kumar", imageUrl: "https://picsum.photos/seed/gvprakash/200/200" },
    { name: "D. Imman", imageUrl: "https://picsum.photos/seed/imman/200/200" },
    { name: "Devi Sri Prasad", imageUrl: "https://picsum.photos/seed/dsp/200/200" },
    { name: "Thaman S", imageUrl: "https://picsum.photos/seed/thaman/200/200" },
    { name: "M. M. Keeravani", imageUrl: "https://picsum.photos/seed/keeravani/200/200" },
    { name: "Anup Rubens", imageUrl: "https://picsum.photos/seed/anup/200/200" },
    { name' "Hesham Abdul Wahab", imageUrl: "https://picsum.photos/seed/hesham/200/200" },
    { name: "Gopi Sundar", imageUrl: "https://picsum.photos/seed/gopi/200/200" },
    { name: "Shaan Rahman", imageUrl: "https://picsum.photos/seed/shaanrahman/200/200" },
    { name: "Jassie Gill", imageUrl: "https://picsum.photos/seed/jassie/200/200" },
    { name: "Ammy Virk", imageUrl: "https://picsum.photos/seed/ammy/200/200" },
    { name: "Hardy Sandhu", imageUrl: "https://picsum.photos/seed/hardy/200/200" },
    { name: "AP Dhillon", imageUrl: "https://picsum.photos/seed/apdhillon/200/200" },
    { name: "Shubh", imageUrl: "https://picsum.photos/seed/shubh/200/200" },
    { name: "Karan Aujla", imageUrl: "https://picsum.photos/seed/karanaujla/200/200" },
    { name: "Parmish Verma", imageUrl: "https://picsum.photos/seed/parmish/200/200" },
    { name: "Prateek Kuhad", imageUrl: "https://picsum.photos/seed/prateek/200/200" },
    { name: "Ritviz", imageUrl: "https://picsum.photos'seed/ritviz/200/200" },
    { name: "Sachin-Jigar", imageUrl: "https://picsum.photos/seed/sachinjigar/200/200" },
    { name: "Meet Bros", imageUrl: "https://picsum.photos/seed/meetbros/200/200" },
    { name: "Tony Kakkar", imageUrl: "https://picsum.photos/seed/tonykakkar/200/200" },
    { name: "Emiway Bantai", imageUrl: "https://picsum.photos/seed/emiway/200/200" },
    { name: "Divine", imageUrl: "https://picsum.photos/seed/divine/200/200" },
    { name: "Raftaar", imageUrl: "https://picsum.photos/seed/raftaar/200/200" },
    { name: "MC Stan", imageUrl: "https://picsum.photos/seed/mcstan/200/200" },
    { name: "King", imageUrl: "https://picsum.photos/seed/king/200/200" },
    { name: "Khesari Lal Yadav", imageUrl: "https://picsum.photos/seed/khesari/200/200" },
    { name: "Pawan Singh", imageUrl: "https://picsum.photos/seed/pawan/200/200" },
    { name: "Sapna Choudhary", imageUrl: "https://picsum.photos/seed/sapna/200/200" },
    { name: "Gulzaar Chhaniwala", imageUrl: "https://picsum.photos/seed/gulzaar/200/200" },
    { name: "Mame Khan", imageUrl: "https://picsum.photos/seed/mamekhan/200/200" },
    { name: "Falguni Pathak", imageUrl: "https://picsum.photos/seed/falguni/200/200" },
    { name: "Shantanu Moitra", imageUrl: "https://picsum.photos/seed/shantanu/200/200" },
    { name: "Jasleen Royal", imageUrl: "https://picsum.photos/seed/jasleen/200/200" },
    { name: "Monali Thakur", imageUrl: "https://picsum.photos/seed/monali/200/200" },
    { name: "Neeti Mohan", imageUrl: "https://picsum.photos/seed/neeti/200/200" },
    { name: "Palak Muchhal", imageUrl: "https://picsum.photos/seed/palak/200/200" },
    { name: "Shirley Setia", imageUrl: "https://picsum.photos/seed/shirley/200/200" },
    { name: "Jonita Gandhi", imageUrl: "https://picsum.photos/seed/jonita/200/200" },
    { name: "Asees Kaur", imageUrl: "https://picsum.photos/seed/asees/200/200" },
    { name: "Benny Dayal", imageUrl: "https://picsum.photos/seed/benny/200/200" },
    { name: "Nakash Aziz", imageUrl: "https://picsum.photos/seed/nakash/200/200" },
    { name: "Tochi Raina", imageUrl: "https://picsum.photos/seed/tochi/200/200" },
    { name: "Rekha Bhardwaj", imageUrl: "https://picsum.photos/seed/rekha/200/200" },
    { name: "Sanam Puri", imageUrl: "https://picsum.photos/seed/sanampuri/200/200" },
    { name: "When Chai Met Toast", imageUrl: "https://picsum.photos/seed/wcmt/200/200" },
    { name: "The Local Train", imageUrl: "https://picsum.photos/seed/localtrain/200/200" },
    { name: "Indian Ocean", imageUrl: "https://picsum.photos/seed/indianocean/200/200" },
    { name: "Parikrama", imageUrl: "https://picsum.photos/seed/parikrama/200/200" },
    { name: "Agnee", imageUrl: "https://picsum.photos/seed/agneee/200/200" },
    { name: "Swarathma", imageUrl: "https://picsum.photos/seed/swarathma/200/200" },
    { name: "Advaita", imageUrl: "https://picsum.photos/seed/advaita/200/200" },
    { name: "B Praak", imageUrl: "https://picsum.photos/seed/bpraak/200/200" },
    { name: "Jaani", imageUrl: "https://picsum.photos/seed/jaani/200/200" },
    { name: "Akhil", imageUrl: "https://picsum.photos/seed/akhil/200/200" },
    { name: "Sachet Tandon", imageUrl: "https://picsum.photos/seed/sachet/200/200" },
    { name: "Parampara Thakur", imageUrl: "https://picsum.photos/seed/parampara/200/200" },
    { name: "Stebin Ben", imageUrl: "https://picsum.photos/seed/stebin/200/200" },
];
