
export const genres = [
  // ** India & Bollywood **
  'Bollywood',
  'Hindi Pop',
  'Punjabi Pop',
  'Bhangra',
  'Tamil Pop',
  'Telugu Pop',
  'Kannada Pop',
  'Malayalam Pop',
  'Marathi Pop',
  'Gujarati Pop',
  'Bengali Pop',
  'Sufi',
  'Ghazal',
  'Indian Classical',
  'Carnatic Music',
  'Hindustani Classical',
  'Indian Folk',
  'Qawwali',
  'Bollywood Remix',
  '90s Bollywood',
  '2000s Bollywood',
  'Sad Bollywood',
  'Romantic Bollywood',
  'Patriotic',
  'Bhojpuri',
  'Haryanvi',
  'Rajasthani',

  // ** Global Pop & Urban **
  'Pop',
  'K-Pop',
  'J-Pop',
  'C-Pop',
  'Hip-Hop',
  'Rap',
  'Trap',
  'R&B',
  'Soul',
  'Funk',
  'Disco',
  'Afrobeats',
  'Reggaeton',
  'Latin Pop',
  'Dancehall',
  
  // ** Electronic & Dance **
  'EDM',
  'House',
  'Deep House',
  'Tropical House',
  'Techno',
  'Trance',
  'Psytrance',
  'Dubstep',
  'Drum and Bass',
  'Hardstyle',
  'Big Room',
  'Electro',
  'Ambient',
  'Downtempo',
  'Chillwave',
  'Synthwave',
  'Vaporwave',
  'UK Garage',

  // ** Rock & Alternative **
  'Rock',
  'Classic Rock',
  'Hard Rock',
  'Alternative Rock',
  'Indie Rock',
  'Punk Rock',
  'Metal',
  'Heavy Metal',
  'Death Metal',
  'Progressive Rock',
  'Psychedelic Rock',
  'Gothic Rock',

  // ** Mood & Vibe **
  'Chill',
  'Lo-fi Hip Hop',
  'Acoustic',
  'Instrumental',
  'Sad Songs',
  'Happy Hits',
  'Workout',
  'Party',
  'Focus',
  'Sleep',
  'Meditation',
  'Gaming',
  'Road Trip',
  'Romantic',
  'Breakup',
  'Motivation',
  'Feel Good',
  'Summer',
  'Winter',
  'Rainy Day',

  // ** Jazz, Blues & Classical **
  'Jazz',
  'Smooth Jazz',
  'Blues',
  'Classical',
  'Opera',
  'Orchestral',
  'Piano',
  'Violin',

  // ** Folk & Country **
  'Folk',
  'Country',
  'Bluegrass',
  'Americana',

  // ** World & Reggae **
  'Reggae',
  'Ska',
  'World Music',
  'Celtic',
  'African Music',
  'Salsa',
  'Bossa Nova',

  // ** Era-Specific **
  '50s',
  '60s',
  '70s',
  '80s',
  '90s',
  '2000s',
  '2010s',
  'Retro',
  
  // ** Niche & Others **
  'Soundtracks',
  'Anime',
  'Kids Music',
  'Christian',
  'Gospel',
  'Christmas',
  'Phonk',
  'Hyperpop',
  'Bedroom Pop',
  'Spoken Word',
  'Comedy',
  
  // Add more specific sub-genres if needed
  'Melodic Dubstep',
  'Liquid Drum and Bass',
  'Future Bass',
  'Chicago House',
  'Acid Techno',
  'Goa Trance',
  'Alternative Metal',
  'Indie Pop',
  'Folk Rock',
  'Country Pop',
  'Delta Blues',
  'Big Band',
  'Baroque',
  'Minimalist',
  'Flamenco',
  'Tango',
  'Kizomba',
  'Zouk',
  'Highlife',
  'Juju',
  'Mbalax',
  'Sea Shanties',
  'Mongolian Throat Singing',

  // Even more specific Indian genres
  'Tollywood',
  'Kollywood',
  'Sandalwood',
  'Mollywood',
  'Rabindra Sangeet',
  'Lavani',
  'Dandiya',
  'Garba',
  'Bihu',
  'Baul',
];
